-- TABLE
DROP
    TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
 -- COLUMNS,
 `id` INT NOT NULL AUTO_INCREMENT,
 `age` INT,
 `date_of_born` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 `name` VARCHAR(64) NOT NULL,
 `job` VARCHAR(64) NOT NULL,
 `notes` VARCHAR(256) DEFAULT '',
 `status` TINYINT DEFAULT '1', 
 `flag` TINYINT DEFAULT '0',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 -- INDEX
 PRIMARY KEY (`id`) -- FOR FOREIGN KEY
) ENGINE = INNODB;

-- TABLE
DROP
    TABLE IF EXISTS `transaction`;
CREATE TABLE IF NOT EXISTS `transaction` (
 -- COLUMNS,
 `id` INT NOT NULL AUTO_INCREMENT,
 `fk_category_id` INT,
 `amount` INT NOT NULL,
 `name` VARCHAR(64) NOT NULL,
 `notes` VARCHAR(256) DEFAULT '',
 `status` TINYINT DEFAULT '1', 
 `flag` TINYINT DEFAULT '0',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 -- INDEX
 PRIMARY KEY (`id`) -- FOR FOREIGN KEY
) ENGINE = INNODB;


